#!/usr/bin/env python3

import sys
import re

# Workaround glib-compile-resources dependency file issue https://gitlab.gnome.org/GNOME/glib/-/issues/2829
if len(sys.argv) != 4:
    print("Usage: python3 script.py GResource.deps GResourceFile.xml Parent")
    sys.exit(1)

deps_file = sys.argv[1]
xml_file = sys.argv[2]
parent_path = sys.argv[3]
c_file = f"{xml_file[:-4]}.c"

with open(deps_file, 'r+') as file:
    content = file.read()
    # Also workaround ninja expecting relative paths as targets in deps files
    relative_c_file = re.sub(f'{re.escape(parent_path)}/?', '', c_file)
    updated_content = re.sub(f'({re.escape(xml_file)}):', f'{relative_c_file}: {xml_file}', content)
    file.seek(0)
    file.write(updated_content)
    file.truncate()
